(function () {
  'use strict';
  var state = { lat:null, lon:null, key:localStorage.getItem('deskClockQWeatherKey') || '', host:localStorage.getItem('deskClockQWeatherHost') || '', weather:null, weatherProvider:'基础天气', astronomy:null, alertId:null, alertTimer:null, audio:null, selectedDate:new Date(), termStart:new Date(2026,7,31) };
  var weekdays = ['日','一','二','三','四','五','六'];
  function el(id) { return document.getElementById(id); }
  function pad(n) { return n < 10 ? '0' + n : String(n); }
  function nowClock() { var d=new Date(); el('time').textContent=pad(d.getHours())+':'+pad(d.getMinutes()); el('seconds').textContent=pad(d.getSeconds()); el('date').textContent=d.getFullYear()+' 年 '+(d.getMonth()+1)+' 月 '+d.getDate()+' 日 星期'+weekdays[d.getDay()]; applyTheme(); renderCourses(); }
  function applyTheme() { var d=new Date(), sun=state.astronomy, dark=d.getHours()<6 || d.getHours()>=19; if(sun && sun.sunrise && sun.sunset) { var day=d.toISOString().slice(0,10); var rise=new Date(day+'T'+sun.sunrise), set=new Date(day+'T'+sun.sunset); dark=d<rise || d>=set; } document.body.className=dark?'dark':''; }
  function icon(code) { code=String(code); if(code==='100')return '☀️'; if(code==='101'||code==='102'||code==='103')return '🌤️'; if(code.indexOf('3')===0)return '🌧️'; if(code.indexOf('4')===0)return '❄️'; if(code.indexOf('5')===0)return '🌫️'; if(code.indexOf('2')===0)return '💨'; return '☁️'; }
  function renderWeather(w, days) { var out='<span class="weather-icon">'+icon(w.icon||w.weathercode)+'</span><div><span class="weather-temp">'+Math.round(w.temp)+'°</span></div><div class="weather-detail">'+(w.text||w.description||'')+'<br>体感 '+Math.round(w.feelsLike||w.apparent_temperature||w.temp)+'°　湿度 '+(w.humidity||'--')+'%</div>'; el('weatherContent').innerHTML=out; el('weatherUpdated').textContent=state.weatherProvider+' · 刚刚更新'; if(days) { el('forecast').innerHTML=days.map(function(x,i){return '<div class="day">'+(i===0?'今天':i===1?'明天':'后天')+'<span>'+icon(x.icon||x.weathercode)+'</span><strong>'+Math.round(x.max)+'°</strong>'+Math.round(x.min)+'°</div>';}).join(''); } }
  function fetchOpenMeteo() { var url='https://api.open-meteo.com/v1/forecast?latitude='+state.lat+'&longitude='+state.lon+'&current=temperature_2m,relative_humidity_2m,apparent_temperature,weather_code&daily=weather_code,temperature_2m_max,temperature_2m_min,sunrise,sunset&timezone=auto&forecast_days=3'; fetch(url).then(function(r){return r.json();}).then(function(x){ state.weatherProvider='基础天气';state.astronomy={sunrise:x.daily.sunrise[0].slice(11,16),sunset:x.daily.sunset[0].slice(11,16)}; renderWeather({temp:x.current.temperature_2m,apparent_temperature:x.current.apparent_temperature,humidity:x.current.relative_humidity_2m,weathercode:x.current.weather_code,text:weatherText(x.current.weather_code)}, x.daily.time.map(function(_,i){return {weathercode:x.daily.weather_code[i],max:x.daily.temperature_2m_max[i],min:x.daily.temperature_2m_min[i]};})); applyTheme(); }).catch(weatherFailed); }
  function weatherText(n) { return n===0?'晴':n<=3?'多云':n<=48?'有雾':n<=67?'有雨':n<=77?'降雪':n<=82?'阵雨':n<=86?'阵雪':'雷暴'; }
  function showLocationName(item){if(!item)return;var parts=[item.adm1,item.adm2,item.name].filter(function(v,i,a){return v&&a.indexOf(v)===i;});if(parts.length)el('locationName').textContent=parts.join(' · ');}
  function fetchLocationName(){var coord=state.lon.toFixed(2)+','+state.lat.toFixed(2),host=qWeatherHost();if(state.key&&host){qWeatherJSON('https://'+host+'/geo/v2/city/lookup?location='+coord+'&range=cn&lang=zh&key='+encodeURIComponent(state.key)).then(function(x){if(x.code==='200'&&x.location&&x.location[0])showLocationName(x.location[0]);else throw new Error('No location');}).catch(fetchOpenStreetMapLocation);return;}fetchOpenStreetMapLocation();}
  function fetchOpenStreetMapLocation(){var url='https://nominatim.openstreetmap.org/reverse?format=jsonv2&accept-language=zh-CN&zoom=10&lat='+state.lat+'&lon='+state.lon;fetch(url).then(function(r){return r.json();}).then(function(x){var a=x.address||{};showLocationName({name:a.city||a.town||a.county||a.city_district||a.state_district,adm2:a.state,adm1:a.country});}).catch(function(){el('locationName').textContent='东经'+state.lon.toFixed(2)+'° · 北纬'+state.lat.toFixed(2)+'°';});}
  function qWeatherJSON(url){return fetch(url).then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.json();});}
  function qWeatherHost(){var host=state.host.replace(/^https?:\/\//,'').replace(/\/$/,'');return /^[a-z0-9.-]+\.qweatherapi\.com$/i.test(host)?host:'';}
  function fetchQWeather() { var host=qWeatherHost();if(!host){fetchOpenMeteo();return;}var base='https://'+host+'/v7/', coord=state.lon.toFixed(2)+','+state.lat.toFixed(2)+'&key='+encodeURIComponent(state.key), today=(new Date()).toISOString().slice(0,10).replace(/-/g,''); Promise.all([qWeatherJSON(base+'weather/now?location='+coord),qWeatherJSON(base+'weather/3d?location='+coord),qWeatherJSON(base+'astronomy/sun?location='+coord+'&date='+today).catch(function(){return null;}),qWeatherJSON(base+'warning/now?location='+coord).catch(function(){return null;})]).then(function(v){if(v[0].code!=='200'||v[1].code!=='200')throw new Error('QWeather response');var n=v[0].now, sun=v[2];state.weatherProvider='和风天气';state.astronomy=sun&&sun.code==='200'&&sun.sunrise?{sunrise:sun.sunrise.slice(11,16),sunset:sun.sunset.slice(11,16)}:null;renderWeather({temp:n.temp,feelsLike:n.feelsLike,humidity:n.humidity,icon:n.icon,text:n.text},v[1].daily.map(function(d){return {icon:d.iconDay,max:d.tempMax,min:d.tempMin};}));applyTheme();if(v[3]&&v[3].code==='200'&&v[3].warning&&v[3].warning.length)showAlert(v[3].warning[0]);if(!state.astronomy)fetchOpenMeteoSun();}).catch(function(){fetchOpenMeteo();}); }
  function fetchOpenMeteoSun(){var url='https://api.open-meteo.com/v1/forecast?latitude='+state.lat+'&longitude='+state.lon+'&daily=sunrise,sunset&timezone=auto&forecast_days=1';fetch(url).then(function(r){return r.json();}).then(function(x){state.astronomy={sunrise:x.daily.sunrise[0].slice(11,16),sunset:x.daily.sunset[0].slice(11,16)};applyTheme();});}
  function bandoriType(type){return {story:'普通活动',challenge:'挑战活动',versus:'对战活动',festival:'协力演出活动',mission_live:'任务演出',live_try:'TRY! 演出',medley:'组曲演出',live_goals:'目标演出'}[type]||'游戏活动';}
  function bandoriDate(ms){var d=new Date(Number(ms));return (d.getMonth()+1)+'月'+d.getDate()+'日 '+pad(d.getHours())+':'+pad(d.getMinutes());}
  function bandoriCountdown(ms){var diff=Math.max(0,Number(ms)-Date.now()),hours=Math.floor(diff/3600000),days=Math.floor(hours/24);return days?'剩余 '+days+' 天 '+(hours%24)+' 小时':'剩余 '+Math.floor(diff/60000)+' 分钟';}
  function renderBandori(event,id,status){var name=event.eventName[3]||event.eventName[0]||'活动信息暂缺',start=event.startAt[3],end=event.endAt[3],text='<div class="bandori-status">'+status+' · '+bandoriType(event.eventType)+'</div><div class="bandori-name">'+escapeHtml(name)+'</div><div class="bandori-meta">'+bandoriDate(start)+' — '+bandoriDate(end)+'</div>';if(status==='当前活动')text+='<div class="bandori-countdown">'+bandoriCountdown(end)+'</div>';el('bandoriContent').innerHTML=text;try{localStorage.setItem('deskClockBandoriEvent',JSON.stringify({event:event,id:id,status:status,at:Date.now()}));}catch(e){}}
  function fetchBandoriEvent(){var cache;try{cache=JSON.parse(localStorage.getItem('deskClockBandoriEvent')||'null');}catch(e){}if(cache&&Date.now()-cache.at<60*60*1000){renderBandori(cache.event,cache.id,cache.status);return;}fetch('https://bestdori.com/api/events/all.6.json').then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(function(events){var now=Date.now(),current=null,next=null,id,key,e;for(key in events){if(events.hasOwnProperty(key)){e=events[key];if(!e.startAt||!e.startAt[3]||!e.endAt||!e.endAt[3])continue;if(Number(e.startAt[3])<=now&&Number(e.endAt[3])>now){current={event:e,id:key};break;}if(Number(e.startAt[3])>now&&(!next||Number(e.startAt[3])<Number(next.event.startAt[3])))next={event:e,id:key};}}if(current)renderBandori(current.event,current.id,'当前活动');else if(next)renderBandori(next.event,next.id,'下期活动');else el('bandoriContent').innerHTML='<p class="empty">暂未找到简中服活动数据</p>';}).catch(function(){if(cache){renderBandori(cache.event,cache.id,cache.status);}else el('bandoriContent').innerHTML='<p class="empty">暂时无法获取活动信息</p>';});}
  function weatherFailed() { el('weatherContent').textContent='暂时无法获取天气。请检查网络或定位权限。'; }
  function refreshWeather() { if(state.lat===null)return; if(state.key&&qWeatherHost()) fetchQWeather(); else fetchOpenMeteo(); }
  function warningMeta(a) { var source=(a.typeName||'')+(a.title||''), type='气象', asset='rain storm', level=a.level||''; if(/台风/.test(source)){type='台风';asset='typhoon';}else if(/暴雨/.test(source)){type='暴雨';asset='rain storm';}else if(/暴雪/.test(source)){type='暴雪';asset='snow storm';}else if(/寒潮|低温/.test(source)){type='寒潮';asset='cold wave';}else if(/大风/.test(source)){type='大风';asset='gale';}else if(/沙尘/.test(source)){type='沙尘暴';asset='sand storm';}else if(/高温/.test(source)){type='高温';asset='heat wave';}else if(/干旱/.test(source)){type='干旱';asset='drought';}else if(/雷电/.test(source)){type='雷电';asset='lightening';}else if(/冰雹/.test(source)){type='冰雹';asset='hail';}else if(/霜冻/.test(source)){type='霜冻';asset='frost';}else if(/大雾/.test(source)){type='大雾';asset='heavy fog';}else if(/霾/.test(source)){type='霾';asset='haze';}else if(/道路结冰/.test(source)){type='道路结冰';asset='road icing';} if(!level){if(/红色/.test(source))level='红色';else if(/橙色/.test(source))level='橙色';else if(/黄色/.test(source))level='黄色';else level='蓝色';} var names={"蓝色":"Blue","黄色":"Yellow","橙色":"Orange","红色":"Red"}, color=level==='红色'?'#e32119':level==='橙色'?'#ed7d18':level==='黄色'?'#f5dc18':'#3989d0'; return {type:type,asset:asset,level:level,color:color,englishLevel:names[level]||'Blue'}; }
  function warningIcon(m) { var file=m.englishLevel+' '+m.asset+' alert - China.svg', src='https://commons.wikimedia.org/wiki/Special:FilePath/'+encodeURIComponent(file); return '<img class="warning-icon" src="'+src+'" alt="'+escapeHtml(m.type+m.level+'预警信号')+'">'; }
  function showAlert(a) { var id=a.id||a.title; if(id===state.alertId)return; state.alertId=id; var title=a.title||'天气预警', text=a.text||a.description||'', meta=warningMeta(a), full=meta.level==='橙色'||meta.level==='红色'; document.documentElement.style.setProperty('--alert-color',meta.color); el('alertLevel').textContent=(a.typeName||meta.type)+' · '+meta.level+'预警'; el('alertTitle').textContent=title; el('alertText').textContent=text; el('alertFullIcon').innerHTML=warningIcon(meta); el('alertCorner').innerHTML=warningIcon(meta); el('alertCorner').hidden=false; clearTimeout(state.alertTimer); if(full){el('alertOverlay').hidden=false;state.alertTimer=setTimeout(function(){el('alertOverlay').hidden=true;},10000);}else{el('alertOverlay').hidden=true;} if(meta.level==='红色') beep(5); }
  function escapeHtml(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function unlockAudio() { var C=window.AudioContext||window.webkitAudioContext;if(!C||state.audio)return; try { state.audio=new C(); var o=state.audio.createOscillator(), g=state.audio.createGain(); g.gain.value=0; o.connect(g); g.connect(state.audio.destination); o.start(); o.stop(state.audio.currentTime+.01); if(state.audio.resume)state.audio.resume(); }catch(e){} }
  function beep(seconds) { var C=window.AudioContext||window.webkitAudioContext,c=state.audio;if(!C)return; try {c=c||new C();state.audio=c;if(c.resume)c.resume();var o=c.createOscillator(),g=c.createGain();o.frequency.value=880;g.gain.value=.08;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+seconds);}catch(e){} }
  function parseCSV(t) { var rows=[],row=[],v='',quote=false,i,c; for(i=0;i<t.length;i++){c=t.charAt(i);if(c==='"'){if(quote&&t.charAt(i+1)==='"'){v+='"';i++;}else quote=!quote;}else if(c===','&&!quote){row.push(v.trim());v='';}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&t.charAt(i+1)==='\n')i++;row.push(v.trim());if(row.join(''))rows.push(row);row=[];v='';}else v+=c;}row.push(v.trim());if(row.join(''))rows.push(row); var h=rows.shift().map(function(x){return x.replace(/^\uFEFF/,'').toLowerCase();}); return rows.map(function(r){var o={};h.forEach(function(k,j){o[k]=r[j]||'';});return o;}); }
  function getCourses(){var preset=window.PRESET_COURSES||[];try{var saved=JSON.parse(localStorage.getItem('deskClockCourses')||'[]');if(saved.length&&preset.length)return preset.concat(saved);return saved.length?saved:preset;}catch(e){return preset;}}
  function courseWeekday(x){var w=x.weekday;if(typeof w==='number')return w;w=x['星期']||x['星期几']||x['weekday']||'';var names=['周日','周一','周二','周三','周四','周五','周六'];for(var i=0;i<names.length;i++){if(w===names[i]||w===('星期'+weekdays[i])||w===weekdays[i]||w===String(i))return i;}return -1;}
  function termWeek(d){var oneDay=24*60*60*1000, start=new Date(state.termStart.getFullYear(),state.termStart.getMonth(),state.termStart.getDate()), target=new Date(d.getFullYear(),d.getMonth(),d.getDate()), diff=Math.floor((target-start)/oneDay);return diff<0?0:Math.floor(diff/7)+1;}
  function isCourseActive(x,week){var range=x.weeks||x['周次']||'';if(!range)return true;var m=String(range).match(/(\d+)\s*(?:-|—|至)\s*(\d+)/);if(m)return week>=parseInt(m[1],10)&&week<=parseInt(m[2],10);m=String(range).match(/(\d+)/);return m?week===parseInt(m[1],10):true;}
  function renderCourses(){var d=state.selectedDate, today=new Date(), isToday=d.getFullYear()===today.getFullYear()&&d.getMonth()===today.getMonth()&&d.getDate()===today.getDate(), week=termWeek(d), data=getCourses().filter(function(x){return courseWeekday(x)===d.getDay()&&isCourseActive(x,week);});el('courseDate').textContent=(isToday?'今天 · ':'')+(d.getMonth()+1)+'月'+d.getDate()+'日 · 星期'+weekdays[d.getDay()]+(week?' · 第'+week+'周':' · 学期未开始');el('courseList').innerHTML=data.length?data.map(function(x){var start=x.start||x['开始时间']||x['时间']||'',end=x.end||x['结束时间']||'',place=x.place||x['地点']||x['教室']||x['location']||'',teacher=x.teacher||'',weeks=x.weeks||x['周次']||'';return '<div class="course"><div class="course-time">'+escapeHtml(start)+(end?'–'+escapeHtml(end):'')+'</div><div><div class="course-name">'+escapeHtml(x.name||x['课程名称']||x['课程']||x['名称']||x['course']||'未命名课程')+'</div><div class="course-place">'+escapeHtml([teacher,place,weeks].filter(function(v){return v;}).join(' · '))+'</div></div></div>';}).join(''):'<p class="empty">'+(week?'这一天没有课程安排':'学期尚未开始')+'</p>';}
  el('csvInput').addEventListener('change',function(e){var f=e.target.files[0];if(!f)return;var r=new FileReader();r.onload=function(){try{localStorage.setItem('deskClockCourses',JSON.stringify(parseCSV(r.result)));renderCourses();}catch(err){alert('CSV 文件无法读取，请检查格式。');}};r.readAsText(f,'utf-8');});
  el('settingsButton').onclick=function(){el('apiKeyInput').value=state.key;el('apiHostInput').value=state.host;el('settingsModal').hidden=false;};el('closeSettings').onclick=function(){el('settingsModal').hidden=true;};el('saveSettings').onclick=function(){state.key=el('apiKeyInput').value.trim();state.host=el('apiHostInput').value.trim();localStorage.setItem('deskClockQWeatherKey',state.key);localStorage.setItem('deskClockQWeatherHost',state.host);el('settingsModal').hidden=true;refreshWeather();};el('clearCourses').onclick=function(){localStorage.removeItem('deskClockCourses');renderCourses();};el('dismissAlert').onclick=function(){el('alertOverlay').hidden=true;el('alertCorner').hidden=false;clearTimeout(state.alertTimer);};el('prevDay').onclick=function(){state.selectedDate.setDate(state.selectedDate.getDate()-1);renderCourses();};el('nextDay').onclick=function(){state.selectedDate.setDate(state.selectedDate.getDate()+1);renderCourses();};el('todayButton').onclick=function(){state.selectedDate=new Date();renderCourses();};
  function locate(){if(!navigator.geolocation){weatherFailed();return;}navigator.geolocation.getCurrentPosition(function(p){state.lat=p.coords.latitude;state.lon=p.coords.longitude;el('locationName').textContent='正在识别位置';fetchLocationName();refreshWeather();},function(){el('locationName').textContent='未获取定位';weatherFailed();},{enableHighAccuracy:true,timeout:12000,maximumAge:600000});}
  document.addEventListener('touchstart',unlockAudio,false);document.addEventListener('click',unlockAudio,false);
  nowClock();setInterval(nowClock,1000);locate();setInterval(refreshWeather,5*60*1000);fetchBandoriEvent();setInterval(fetchBandoriEvent,60*60*1000);
}());
